name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      BRANCH_NAME:
        type: string
        default: main
        description: Git branch to build
      BUILD_TYPE:
        type: select
        options:
          - development
          - staging
          - production
        description: Build environment type
      RUN_TESTS:
        type: boolean
        default: true
        description: Run tests before building
      PUSH_IMAGE:
        type: boolean
        default: true
        description: Push Docker image to registry

env:
  APP_NAME: my-application
  DOCKER_IMAGE: "my-registry/${{APP_NAME}}:${{GITHUB_RUN_ID}}"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build with Makefile
        run: |
          make build ENV=${{ inputs.BUILD_TYPE }}
          
      - name: Run Tests
        if: inputs.RUN_TESTS == 'true'
        run: |
          make test

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ env.DOCKER_IMAGE }} \
            --build-arg ENV=${{ inputs.BUILD_TYPE }} \
            .
            
      - name: Push Docker Image to Registry
        if: inputs.PUSH_IMAGE == 'true'
        run: |
          echo "${{ secrets.Docker_Registry_Password }}" | docker login -u ${{ secrets.Docker_Registry_Username }} --password-stdin my-registry
          docker push ${{ env.DOCKER_IMAGE }}
          
          if [ "${{ inputs.BRANCH_NAME }}" == "main" ]; then
            docker tag ${{ env.DOCKER_IMAGE }} my-registry/${{APP_NAME}}:latest
            docker push my-registry/${{APP_NAME}}:latest
          fi

      - name: Post Build Steps
        run: |
          echo 'Build succeeded!'
